Solution
mate-academy/qa_cypress_e2e_simple_auth pull request #164
Opened 2023-01-08 18:34 UTC by MarinaT-N

2023-01-08 19:38 UTC, NataliiaSolotva commented on cypress/e2e/login.cy.js
> +  it('should does not allow USER to Login with invalid creds', () => {
```suggestion
  it('should not allow USER to Login with invalid creds', () => {
```

2023-01-08 19:45 UTC, NataliiaSolotva commented on cypress/e2e/login.cy.js
> +    const password = `${randomNuber}asd!Q`;
Create also separate tests for login with invalid username and for login invalid password

2023-01-08 19:51 UTC, NataliiaSolotva requested changes
Check the comments, please.
The next time don't push all changed files. We do not need node_modules directory here)

2023-01-08 20:13 UTC, MarinaT-N commented on cypress/e2e/login.cy.js
> +  it('should does not allow USER to Login with invalid creds', () => {
done

2023-01-08 20:14 UTC, MarinaT-N commented on cypress/e2e/login.cy.js
> +    const password = `${randomNuber}asd!Q`;
i have created 2 more tests, but i didn't delete the test with all invalid creds.

2023-01-09 11:20 UTC, VadimMentorQA approved these changes
Good job.

2023-01-09 11:21 UTC, VadimMentorQA approved these changes

2023-01-09 11:36 UTC, VadimMentorQA approved these changes

2023-01-31 12:44 UTC, closed without merging