Solution
mate-academy/qa_cypress_e2e_simple_auth pull request #214
Opened 2023-04-07 20:22 UTC by YuriyDmuhail

2023-04-11 11:23 UTC, TarasHorin commented
Good Job!

2023-04-11 11:50 UTC, DimaGaplik approved these changes

2023-04-11 16:41 UTC, tnboyko requested changes

2023-04-11 16:41 UTC, tnboyko commented on cypress/e2e/login.cy.js
> +    cy.get("#flash").should("include.text", " You logged out of the secure area!");
separate these tests - one should be for login only, and one with login and logout in one it

2023-04-11 16:41 UTC, tnboyko commented on cypress/e2e/login.cy.js
> +  it('login with invalid username', () => {
```suggestion
  it('should not allow to login with invalid username', () => {
```

2023-04-11 17:13 UTC, YuriyDmuhail commented on cypress/e2e/login.cy.js
> +    cy.get("#flash").should("include.text", " You logged out of the secure area!");
done

2023-04-12 14:58 UTC, tnboyko approved these changes

2025-09-10 17:07 UTC, closed without merging