Fixed comments
mate-academy/qa_cypress_e2e_simple_auth pull request #318
Opened 2023-07-10 18:21 UTC by Julia14012000

2023-07-12 09:55 UTC, VadimMentorQA requested changes

2023-07-12 09:55 UTC, VadimMentorQA commented on cypress/e2e/signIn.cy.js
> +       .type('tomsmith');
You already have the variable with 'tomsmith' value. Use it here.

2023-07-12 09:55 UTC, VadimMentorQA commented on cypress/e2e/signIn.cy.js
> +   it('should not log in with invalid credentials', () => {
Split this huge test into a few atomic test cases, please

2023-07-14 07:07 UTC, iBrianWarner commented on cypress/e2e/signIn.cy.js
> +       .should('contain.text', 'Login Page');
ти б могла винести дані, що повторюються, винести в обʼєкт і просто його тут передавати. Login Page повторюється 5 разів, Secure Area теж кілька разів.

2023-07-14 07:24 UTC, Julia14012000 commented on cypress/e2e/signIn.cy.js
> +       .should('contain.text', 'Login Page');
дякую, я зрозуміла, додала, ще одиин комітю

2023-07-14 07:25 UTC, Julia14012000 commented on cypress/e2e/signIn.cy.js
> +       .type('tomsmith');
fixed

2023-07-14 07:25 UTC, Julia14012000 commented on cypress/e2e/signIn.cy.js
> +   it('should not log in with invalid credentials', () => {
fixed

2023-07-14 07:59 UTC, closed without merging